### ISSUE TITLE
Error on the worst and average time complexity of Stalin Sort

### ISSUE THREAD

**Issue by Erwan-BR** [LoukaDOZ/Sort-renderer#2]
# Description of the issue

In the Stalin sort, the given "worst case" and "average case" are $O(n)$.

# Analysis of this issue:

However, the worst case is a decreasing list. In this case, you stay on the first element and move all elements from right to left by one.

This result in the following operations :
- First time: Moving $n - 1$ elements.
- Second time: Moving $n - 2$ elements.
- Third time: Moving $n - 3$ elements.
- ...
- Penultimate time: Moving 1 element.
- Ultimate time: Not move any elements.

Therefore, the number of opeation is:.

$$
1 + 2 + 3 + \ldots + (n - 3) + (n - 2) + (n - 1) 
= \sum_{i=0}^{n-1} i \\
\quad = \frac{(n - 1) \cdot n}{2} \\
\quad = \frac{1}{2} \cdot n^2 - \frac{1}{2} \cdot n.
$$

With the Big O mathematical operation, we can deduce that the worst complexity is **$O(n^2)$**.

We could also argue the fact that in the average case, the number of operation is still quadratic, thereofre it should also be **$O(n^2)$**.

**Comment by LoukaDOZ** [comment]
I think you misunderstood how Stalin sort is about. It a joke and works by removing any value that prevents having a sorted list. Starting with the first as a comparator, if the 2nd is superior or equal : it is kept and used as the comparator, else : it is deleted. At the end, in every case, we only run through the list one time.

What you are pointing is my implementation of this deletion which is to manually move all the remaining elements from left to right and reducing array size by one, to override the bad value. I agree that I may improve this by using  memcpy or memmove. I'll try it.

**Comment by Erwan-BR** [comment]
I know it is a joke and i was happy to see you implementing it on your beautiful project.

However the complexity of Stalin function is often bad computed even on internet, because they don't think (or they don't care) about the complexity of the call that you have to make.

If you try an exemple on oneCompiler with different size, you have in the worst case: 
- 1 000 elements: 0.03ms
- 10 000 elements: 2.90 ms
- 100 000 elements: 320 ms

We can notice that even with memove, when you multiply by 10 the number of elements, the time complexity is mulitplied by 100.

**Comment by LoukaDOZ** [comment]
yes

**Comment by LoukaDOZ** [comment]
did the changes

**Comment by LoukaDOZ** [comment]
:+1:
